services:
  - type: web
    name: portfolio-amouzou
    runtime: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: EMAIL_USER
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
